"""Aliases y geografía para corregir los datos base del notebook."""

# Se usan los nombres oficiales actuales de algunos equipos y ciudades
TEAM_ALIASES = {"Åland Islands": "Åland", "Saare County": "Saaremaa"}

# `city` no se pliega a ASCII: hacerlo uniría ciudades distintas que sólo
# coinciden al quitar los diacríticos. Estas son las 5 colisiones que produce
# NFKD sobre las 2.064 ciudades, y sólo 3 son la misma ciudad:
#   - `San Jose` (United States) vs `San José` (Costa Rica): distintas.
#   - `Pula` (Croatia) vs `Púla` (Cyprus): distintas.
# Las otras 3 se unifican con el nombre acentuado, que es el oficial.
CITY_ALIASES = {
    "Tananarive": "Antananarivo",
    "Bogota": "Bogotá",
    "Gijon": "Gijón",
    "Valparaiso": "Valparaíso",
}

# Países con un sucesor único y sin ambigüedad.
COUNTRY_ALIASES = {
    "Netherlands Antilles": "Curaçao",
    "Zaïre": "DR Congo",
    "German DR": "Germany",
    "Republic of Ireland": "Ireland",
    "Burma": "Myanmar",
    "Rhodesia": "Zimbabwe",
    "Ceylon": "Sri Lanka",
    "Tanganyika": "Tanzania",
    "Upper Volta": "Burkina Faso",
    "Dahomey": "Benin",
    "Gold Coast": "Ghana",
}

# Los países con varios sucesores (`Soviet Union`, `Yugoslavia`, `Czechoslovakia`,
# `Serbia and Montenegro`, `Zanzibar`) no entran arriba a propósito:
# `normalized_country` conserva su nombre histórico y lo que se corrige es
# `region`, siempre bajo un nombre actual.
COUNTRY_REGIONS = {
    "Africa": (
        "Algeria",
        "Angola",
        "Benin",
        "Belgian Congo",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo",
        "DR Congo",
        "Djibouti",
        "Egypt",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Ethiopia",
        "French Somaliland",
        "Gabon",
        "Gambia",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Ivory Coast",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mali Federation",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Northern Rhodesia",
        "Nyasaland",
        "Portuguese Guinea",
        "Réunion",
        "Rwanda",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Southern Rhodesia",
        "Sudan",
        "Swaziland",
        "São Tomé and Príncipe",
        "Tanzania",
        "Togo",
        "Tunisia",
        "Uganda",
        "United Arab Republic",
        "Zambia",
        "Zanzibar",
        "Zimbabwe",
    ),
    "Asia": (
        "Afghanistan",
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei",
        "Cambodia",
        "China PR",
        "Cyprus",
        "East Timor",
        "Georgia",
        "Hong Kong",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Lebanon",
        "Macau",
        "Malaya",
        "Malaysia",
        "Maldives",
        "Manchuria",
        "Mongolia",
        "Myanmar",
        "Nepal",
        "North Korea",
        "Northern Cyprus",
        "Oman",
        "Pakistan",
        "Palestine",
        "Philippines",
        "Qatar",
        "Saudi Arabia",
        "Singapore",
        "South Korea",
        "Sri Lanka",
        "Syria",
        "Taiwan",
        "Tajikistan",
        "Thailand",
        "Turkey",
        "Turkmenistan",
        "United Arab Emirates",
        "Uzbekistan",
        "Vietnam",
        "Vietnam DR",
        "Vietnam Republic",
        "Yemen",
        "Yemen AR",
        "Yemen DPR",
    ),
    "Caribbean": (
        "Anguilla",
        "Antigua and Barbuda",
        "Aruba",
        "Bahamas",
        "Barbados",
        "Bermuda",
        "Bonaire",
        "British Virgin Islands",
        "Cayman Islands",
        "Cuba",
        "Curaçao",
        "Dominica",
        "Dominican Republic",
        "Grenada",
        "Guadeloupe",
        "Haiti",
        "Jamaica",
        "Martinique",
        "Montserrat",
        "Puerto Rico",
        "Saint Barthélemy",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Martin",
        "Saint Vincent and the Grenadines",
        "Sint Maarten",
        "Trinidad and Tobago",
        "Turks and Caicos Islands",
        "United States Virgin Islands",
    ),
    "Europe": (
        "Alderney",
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bohemia",
        "Bohemia and Moravia",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Czech Republic",
        "Czechoslovakia",
        "Denmark",
        "England",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "France",
        "German DR",
        "Germany",
        "Gibraltar",
        "Greece",
        "Guernsey",
        "Hungary",
        "Iceland",
        "Ireland",
        "Irish Free State",
        "Isle of Man",
        "Italy",
        "Jersey",
        "Kosovo",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Northern Ireland",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "Russia",
        "Saarland",
        "San Marino",
        "Scotland",
        "Serbia",
        "Serbia and Montenegro",
        "Slovakia",
        "Slovenia",
        "Soviet Union",
        "Spain",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "Wales",
        "Yugoslavia",
        "Éire",
    ),
    "North America": (
        "Belize",
        "Canada",
        "Costa Rica",
        "El Salvador",
        "Greenland",
        "Guatemala",
        "Honduras",
        "Mexico",
        "Nicaragua",
        "Panama",
        "United States",
    ),
    "Oceania": (
        "Australia",
        "Cook Islands",
        "Fiji",
        "French Polynesia",
        "Guam",
        "Micronesia",
        "New Caledonia",
        "New Hebrides",
        "New Zealand",
        "Northern Mariana Islands",
        "Palau",
        "Papua New Guinea",
        "Samoa",
        "Solomon Islands",
        "Tahiti",
        "Tonga",
        "Vanuatu",
        "Western Samoa",
    ),
    "South America": (
        "Argentina",
        "Bolivia",
        "Brazil",
        "British Guyana",
        "Chile",
        "Colombia",
        "Ecuador",
        "French Guiana",
        "Guyana",
        "Netherlands Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Uruguay",
        "Venezuela",
    ),
}

REGION = {c: r for r, countries in COUNTRY_REGIONS.items() for c in countries}
